Completed react-accordion-component exercise.
derrick-fleming/c0822-code-solutions pull request #123
Opened 2022-10-26 23:35 UTC by derrick-fleming

https://user-images.githubusercontent.com/109825222/198158293-8124c9ff-65af-4f57-afb5-281cb557a43d.mov

2022-10-26 23:40 UTC, thebearingedge requested changes

2022-10-26 23:40 UTC, thebearingedge commented on react-accordion-component/src/accordion.jsx
> +      doubleClicked: false
You can simplify this a bit. Try tracking only one thing `openHeader`, initially `null`. If the user clicks a header, set the `openHeader`. If they're clicking the same one again, set it back to `null`.

2022-10-29 01:05 UTC, derrick-fleming commented
https://user-images.githubusercontent.com/109825222/198754917-aeb399fb-46de-465e-8414-cd201a526442.mov

2022-10-29 01:06 UTC, thebearingedge approved these changes

2022-10-29 01:10 UTC, merged