Completed css-canvas-medical exercise.
derrick-fleming/c0822-code-solutions pull request #21
Opened 2022-08-27 23:29 UTC by derrick-fleming

https://user-images.githubusercontent.com/109825222/187051361-7a01c7da-5894-4043-a600-9128737361af.mov

<img width="510" alt="Screen Shot 2022-08-27 at 4 26 42 PM" src="https://user-images.githubusercontent.com/109825222/187051383-5f924bfa-156e-40d3-b02c-7d3b0c2e6040.png">

2022-08-28 17:57 UTC, thebearingedge requested changes
Ok, great, just a couple minor adjustments

2022-08-28 17:57 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +}
Rather than constrain the width of the body, try creating a `.page-container` class.

2022-08-28 17:57 UTC, thebearingedge commented on css-canvas-medical/index.html
> +      </div>
Try reworking this to just be two half columns

2022-08-28 23:49 UTC, derrick-fleming commented
https://user-images.githubusercontent.com/109825222/187099739-079d4c8a-2fc1-4a0e-a064-c0c5d8ebe2f4.mov

2022-08-29 16:21 UTC, codingcodymiller requested changes
You have a significant amount of layout classes that have variants named after their section, this is not in line with the structure of proper layout classes. Layout classes are meant to be endlessly reusable, and by naming them after specific sections, they immediately become too unique to reuse. Please revise all `row` and `column` classes to be reusable in all situations. You should only need one `row` class and one `column` class for each size. Any specific behavior should be applied to a separate class that you can add to the element in addition to the `row` or `column` class.

Here is an example: https://codepen.io/codingcodymiller/pen/VwXoYWJ

2022-08-30 04:05 UTC, derrick-fleming commented
https://user-images.githubusercontent.com/109825222/187346784-07539698-877f-4eb1-ae08-12fb1a767d3f.mov

2022-08-30 21:48 UTC, codingcodymiller approved these changes
Great work!!

2022-08-30 21:53 UTC, merged