String manipulation 1
derrick-fleming/c0822-code-solutions pull request #38
Opened 2022-09-02 22:41 UTC by derrick-fleming

![Screen Shot 2022-09-02 at 3 39 47 PM](https://user-images.githubusercontent.com/109825222/188243407-03c26864-63c2-4e0e-9c9b-adf300dd90c2.png)

2022-09-02 23:06 UTC, codingcodymiller requested changes

2022-09-02 23:06 UTC, codingcodymiller commented on string-manipulation-1/src/get-words.js
> +    return getWordsOutput;
You can remove this line, since it would happen on the line below the conditional anyway

2022-09-03 16:08 UTC, derrick-fleming commented
![Screen Shot 2022-09-03 at 9 04 56 AM](https://user-images.githubusercontent.com/109825222/188278942-448f5bb6-e3ad-4310-a394-7a74a7fafe46.png)

2022-09-06 18:17 UTC, codingcodymiller approved these changes

2022-09-06 18:28 UTC, merged