Object manipulation 3
derrick-fleming/c0822-code-solutions pull request #60
Opened 2022-09-17 23:04 UTC by derrick-fleming

![Screen Shot 2022-09-17 at 4 02 01 PM](https://user-images.githubusercontent.com/109825222/190879036-0eea275d-8c0d-4535-8984-f22092b973bc.png)

![Screen Shot 2022-09-17 at 4 02 25 PM](https://user-images.githubusercontent.com/109825222/190879043-84f67abc-d56f-48ab-b766-7f4d1a2f2684.png)

2022-09-19 16:30 UTC, codingcodymiller requested changes

2022-09-19 16:30 UTC, codingcodymiller commented on object-manipulation-3/main.js
> +];
Rather than writing these all out by hand, I would make an array of suits and an array of ranks, then loop over those to generate the deck.

2022-09-20 22:32 UTC, derrick-fleming commented
<img width="1382" alt="Screen Shot 2022-09-20 at 3 30 22 PM" src="https://user-images.githubusercontent.com/109825222/191376574-f0bc4dae-0d78-490c-9f56-6c3d7ae29168.png">

2022-10-09 19:32 UTC, thebearingedge approved these changes

2022-10-10 18:54 UTC, merged